<?php

function recipe_support_form_alter(&$form, &$form_state, $form_id) {
    if($form_id == 'recipe_node_form') {

        $form['comment_settings']['#access'] = 0;
        $form['menu']['#access'] = 0;
        $form['revision_information']['#access'] = 0;
        $form['author']['#access'] = 0;
        $form['options']['#access'] = 0;

        print '<pre>';
        print_r($form);
        print '</pre>';
        print_r($form_id);
    }
}
